### ISSUE TITLE
Webpack dev server doesn't work anymore

### ISSUE THREAD

**Issue by nukerr** [rails/tailwindcss-rails#18]
After following the installation steps, I cannot start webpack-dev-server anymore.
here's the stacktrace:
```
./bin/webpack-dev-server
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /project/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/project/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

**Comment by colinrubbert** [comment]
@nukerr From what I understand this is just for the asset pipeline currently, there isn't a webpack installer built in with the `install` functionality. 

So it supports traditional Rails asset pipeline but NOT webpacker assets. For use with webpacker Tailwinds needs to be installed via webpacker. At least this is my current understanding.

**Comment by vovimayhem** [comment]
I'm replicating the error on a "fresh" Rails 6.1.1 app. The `webpack-cli` version installed is `3.3.12`.

Something during `./bin/rails tailwindcss:install` command is updating the `webpack-cli` npm package to version `4.4.0`, which no longer has the `webpack-cli/bin/config-yargs` path (in the `node_modules` folder)

**Comment by vovimayhem** [comment]
That would be the version or rails/webpacker requiring a version of wepack-cli greater than 4.0.0

**Comment by CuriousPhysicist** [comment]
So I hit this problem this morning and like @vovimayhem I'm on Rails 6.1.1.

The webpack-dev-server was running fine until I ran the `tailwindcss:install` rake task.

A fix which seems to have worked for me (but definitely is a sticking plaster approach) is to run:

`yarn install webpack-cli@3.3.12`

I don't know enough about why it broke to know why this fixed it for me 🤷

If it helps anyone else in the while a fix is worked on then great. :-)

My setup is Macbook on Catelina 10.15.7 (19H114), Ruby - ruby 2.7.2p137 (2020-10-01 revision 5445e04352)

**Comment by BakiVernes** [comment]
Working on a fix!
