### ISSUE TITLE
Issue running bin/dev when creating new project rails new project --css tailwind

### ISSUE THREAD

**Issue by kevincf** [rails/tailwindcss-rails#185]
```
➜  depot git:(main) ✗ bin/dev 
09:25:48 web.1  | started with pid 6454
09:25:48 css.1  | started with pid 6455
09:25:48 css.1  | /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:498:in `materialize': Could not find importmap-rails-1.1.5, turbo-rails-1.1.1, stimulus-rails-1.1.0, tailwindcss-rails-2.0.10-arm64-darwin, bootsnap-1.13.0, msgpack-1.5.4, strscan-3.0.4 in any of the sources (Bundler::GemNotFound)
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:191:in `specs'
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:247:in `specs_for'
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:18:in `setup'
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler.rb:162:in `setup'
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
09:25:48 css.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
09:25:48 css.1  |       from <internal:/Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
09:25:48 css.1  |       from <internal:/Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
09:25:48 web.1  | /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:498:in `materialize': Could not find importmap-rails-1.1.5, turbo-rails-1.1.1, stimulus-rails-1.1.0, tailwindcss-rails-2.0.10-arm64-darwin, bootsnap-1.13.0, msgpack-1.5.4, strscan-3.0.4 in any of the sources (Bundler::GemNotFound)
09:25:48 css.1  |       from /Users/kevon/Documents/projects/ruby/depot/config/boot.rb:3:in `<top (required)>'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:191:in `specs'
09:25:48 css.1  |       from bin/rails:3:in `require_relative'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/definition.rb:247:in `specs_for'
09:25:48 css.1  |       from bin/rails:3:in `<main>'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/runtime.rb:18:in `setup'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler.rb:162:in `setup'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:20:in `block in <top (required)>'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:136:in `with_level'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/ui/shell.rb:88:in `silence'
09:25:48 web.1  |       from /Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/bundler/setup.rb:20:in `<top (required)>'
09:25:48 web.1  |       from <internal:/Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
09:25:48 web.1  |       from <internal:/Users/kevon/.rbenv/versions/3.1.2/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
09:25:48 web.1  |       from /Users/kevon/Documents/projects/ruby/depot/config/boot.rb:3:in `<top (required)>'
09:25:48 web.1  |       from bin/rails:3:in `require_relative'
09:25:48 web.1  |       from bin/rails:3:in `<main>'
09:25:49 css.1  | exited with code 1
09:25:49 system | sending SIGTERM to all processes
09:25:49 web.1  | exited with code 1
```

**Comment by flavorjones** [comment]
Hi! I'm sorry you're having this problem.

Unfortunately, I can't reproduce what you're seeing. It looks like you may not have all the necessary gems installed, so I would recommend running `bundle install` in case that's the cause.

If that doesn't resolve your issue, please respond with a comment that shows:

- the output of `bundle env`
- the output from your `rails new` command

Thank you!
