### ISSUE TITLE
NoMethodError when trying to install tailwindcss-rails

### ISSUE THREAD

**Issue by igaurab** [rails/tailwindcss-rails#399]
Hi I am pretty much new to rails. I am trying to install the  shadcn ui for rails and it had one of it's dependencies as tailwindcss-rails. 

Command issued:

`./bin/rails tailwindcss:install`

Platform: MacOS M3
Ruby version: 3.2.2
Rails: 7.2.1
Issue: NoMethodError: undefined method `to_sym' for nil:NilClass (NoMethodError)

Stacktrace
```
igaurab@Gaurabs-MacBook-Pro-2 clear_pay % ./bin/rails tailwindcss:install --trace
bin/rails aborted!
NoMethodError: undefined method `to_sym' for nil:NilClass (NoMethodError)

      super(key.to_sym)
               ^^^^^^^
/Users/igaurab/.gem/gems/activesupport-7.2.1/lib/active_support/ordered_options.rb:42:in `[]'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations/connection_url_resolver.rb:84:in `resolved_adapter'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations/connection_url_resolver.rb:28:in `initialize'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations/url_config.rb:73:in `new'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations/url_config.rb:73:in `build_url_hash'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations/url_config.rb:44:in `initialize'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:67:in `new'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:67:in `block in <class:DatabaseConfigurations>'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:279:in `block in build_db_config_from_hash'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:278:in `reverse_each'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:278:in `build_db_config_from_hash'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:257:in `build_db_config_from_raw_config'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:208:in `block in build_configs'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:204:in `each'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:204:in `flat_map'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:204:in `build_configs'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/database_configurations.rb:74:in `initialize'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:144:in `new'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/tasks/database_tasks.rb:144:in `for_each'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/railties/databases.rake:35:in `block (2 levels) in <main>'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/task_manager.rb:232:in `in_namespace'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/dsl_definition.rb:142:in `namespace'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/railties/databases.rake:30:in `block in <main>'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/task_manager.rb:232:in `in_namespace'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/dsl_definition.rb:142:in `namespace'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/railties/databases.rake:9:in `<main>'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/railtie.rb:57:in `load'
/Users/igaurab/.gem/gems/activerecord-7.2.1/lib/active_record/railtie.rb:57:in `block in <class:Railtie>'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/railtie.rb:285:in `instance_exec'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/railtie.rb:285:in `block in run_tasks_blocks'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/railtie.rb:297:in `each'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/railtie.rb:297:in `each_registered_block'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/railtie.rb:285:in `run_tasks_blocks'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/application.rb:553:in `block in run_tasks_blocks'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/engine/railties.rb:15:in `each'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/engine/railties.rb:15:in `each'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/application.rb:553:in `run_tasks_blocks'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/engine.rb:470:in `load_tasks'
/Users/igaurab/workspaces/ruby/rails/clear_pay/Rakefile:6:in `<main>'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/application.rb:740:in `raw_load_rakefile'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/application.rb:126:in `block in load_rakefile'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/application.rb:125:in `load_rakefile'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
/Users/igaurab/.gem/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/command.rb:156:in `invoke_rake'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/command.rb:73:in `block in invoke'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/command.rb:149:in `with_argv'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/command.rb:69:in `invoke'
/Users/igaurab/.gem/gems/railties-7.2.1/lib/rails/commands.rb:18:in `<main>'
<internal:/Users/igaurab/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/igaurab/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/igaurab/.gem/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
./bin/rails:4:in `<main>'
```

**Comment by flavorjones** [comment]
Hi @igaurab, I'm sorry you're having this problem. Unfortunately I don't see anything in this error backtrace that's related to the `tailwindcss-rails` gem.

If I was going to guess, I'd say (based on the stack trace) this error message is coming from an incorrectly formatted `database.yml` file, but you may have more luck asking about this in a general Rails forum like https://discuss.rubyonrails.org/

**Comment by igaurab** [comment]
Hi thanks for the response. 

I managed to get it working in a new repository. Mostly issue on my part it seems. 

Thanks.
